version: '3'

volumes:
  nginx_data:
    driver: local
  letsencrypt_data:
    driver: local

services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '8080:80'
      - '81:81'
      - '443:443'
    volumes:
      - nginx_data:/data
      - letsencrypt_data:/etc/letsencrypt
    networks:
      - acn-net

networks:
  acn-net:
    driver: bridge